---
openapi: 3.0.0
info:
  description: free5GC webconsole backend API
  version: v1
  title: Webconsole Backend API
servers:
  - url: http://localhost:5000
tags:
  - name: webconsole
    description: MDM backend API
paths:
  /api/subscriber:
    get:
      tags:
        - webconsole
      summary: Get all subscribers
      description: Returns an array of subscriber.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            format: int64
        - in: query
          name: page
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Returns an array of subscriber.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subscriber"
components:
  schemas:
    # Meta object
    Meta:
      type: object
      properties:
        next:
          type: string
        prev:
          type: string
        limit:
          type: integer
          format: int64
        total:
          type: integer
          format: int64
    # Subscriber
    Subscriber:
      type: object
      properties:
        plmnID:
          type: string
        ueId:
          type: string
    # PduSession
    PduSession:
      type: object
      properties:
        Dnn:
          type: string
        PduSessionId:
          type: string
        Sd:
          type: string
        SmContextRef:
          type: string
        Sst:
          type: string
    # UeContext
    UeContext:
      type: object
      properties:
        AccessType:
          type: string
        CmState:
          type: string
        Guti:
          type: string
        Mcc:
          type: string
        Mnc:
          type: string
        PduSessions:
          type: array
          items:
            $ref: "#/components/schemas/PduSession"
        Supi:
          type: string
        Tac:
          type: string
    # SessionRule
    SessionRule:
      type: object
      properties:
        sessRuleId:
          type: string
    # ANInformation
    ANInformation:
      type: object
      properties:
        IPAddress:
          type: string
        TEID:
          type: integer
          format: int64
    # Tunnel
    Tunnel:
      type: object
      properties:
        ANInformation:
          $ref: "#/components/schemas/ANInformation"
        DataPathPool:
          type: string
        PathIDGenerator:
          type: string
    # PduSessionInfo
    PduSessionInfo:
      type: object
      properties:
        AnType:
          type: string
        Dnn:
          type: string
        LocalSEID:
          type: string
        PDUAddress:
          type: string
        PDUSessionID:
          type: string
        RemoteSEID:
          type: string
        Sd:
          type: string
        SessionRule:
          $ref: "#/components/schemas/SessionRule"
        Sst:
          type: string
        Supi:
          type: string
        Tunnel:
          $ref: "#/components/schemas/Tunnel"
        UpCnxState:
          type: string
    # Tenant
    Tenant:
      type: object
      properties:
        tenantId:
          type: string
        tenantName:
          type: string
    # User
    User:
      type: object
      properties:
        userId:
          type: string
        tenantId:
          type: string
        email:
          type: string
        encryptedPassword:
          type: string
    # Opc
    Opc:
      type: object
      properties:
        opcValue:
          type: string
        encryptionKey:
          type: integer
          format: int64
        encryptionAlgorithm:
          type: integer
          format: int64
    # MilenageOp
    MilenageOp:
      type: object
      properties:
        opValue:
          type: string
        encryptionKey:
          type: integer
          format: int64
        encryptionAlgorithm:
          type: integer
          format: int64
    # Milenage
    Milenage:
      type: object
      properties:
        op:
          $ref: "#/components/schemas/MilenageOp"
    # PermanentKey
    PermanentKey:
      type: object
      properties:
        permanentKeyValue:
          type: string
        encryptionKey:
          type: integer
          format: int64
        encryptionAlgorithm:
          type: integer
          format: int64
    # AuthenticationSubscription
    AuthenticationSubscription:
      type: object
      properties:
        authenticationMethod:
          type: string
        permanentKey:
          $ref: "#/components/schemas/PermanentKey"
        sequenceNumber:
          type: string
        authenticationManagementField:
          type: string
        milenage:
          $ref: "#/components/schemas/Milenage"
        opc:
          $ref: "#/components/schemas/Opc"
    # SubscribedUeAmbr
    SubscribedUeAmbr:
      type: object
      properties:
        uplink:
          type: string
        downlink:
          type: string
    # Nssai
    Nssai:
      type: object
      properties:
        sst:
          type: integer
          format: int64
        sd:
          type: string
    # DefaultSingleNssais
    DefaultSingleNssais:
      type: object
      properties:
        defaultSingleNssais:
          type: array
          items:
            $ref: "#/components/schemas/Nssai"
        singleNssais:
          type: array
          items:
            $ref: "#/components/schemas/Nssai"
    # AccessAndMobilitySubscriptionData
    AccessAndMobilitySubscriptionData:
      type: object
      properties:
        gpsis:
          type: array
          items:
            type: string
        subscribedUeAmbr:
          $ref: "#/components/schemas/SubscribedUeAmbr"
        nssai:
          $ref: "#/components/schemas/DefaultSingleNssais"
    # SessionManagementSubscriptionData
    SessionManagementSubscriptionData:
      type: object
      properties:
        singleNssai:
          $ref: "#/components/schemas/Nssai"
        dnnConfigurations:
          $ref: "#/components/schemas/DnnConfigurations"
    # PduSessionTypes
    PduSessionTypes:
      type: object
      properties:
        defaultSessionType:
          type: string
        allowedSessionTypes:
          type: array
          items:
            type: string
    # SscModes
    SscModes:
      type: object
      properties:
        defaultSscMode:
          type: string
        allowedSscModes:
          type: array
          items:
            type: string
    # Arp
    Arp:
      type: object
      properties:
        priorityLevel:
          type: integer
          format: int64
        preemptCap:
          type: string
        preemptVuln:
          type: string
    # 5gQosProfile
    5gQosProfile:
      type: object
      properties:
        5qi:
          type: integer
          format: int64
        arp:
          $ref: "#/components/schemas/Arp"
        priorityLevel:
          type: integer
          format: int64
    # SessionAmbr
    SessionAmbr:
      type: object
      properties:
        uplink:
          type: string
        downlink:
          type: string
    # UpSecurity
    UpSecurity:
      type: object
      properties:
        upIntegr:
          type: string
        upConfid:
          type: string
    # DnnConfiguration
    DnnConfiguration:
      type: object
      properties:
        pduSessionTypes:
          $ref: "#/components/schemas/PduSessionTypes"
        sscModes:
          $ref: "#/components/schemas/SscModes"
        5gQosProfile:
          $ref: "#/components/schemas/5gQosProfile"
        sessionAmbr:
          $ref: "#/components/schemas/SessionAmbr"
        upSecurity:
          $ref: "#/components/schemas/UpSecurity"
    # DnnConfigurations
    DnnConfigurations:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/DnnConfiguration"
    # Dnn
    Dnn:
      type: object
      properties:
        dnn:
          type: string
    # SubscribedSnssaiInfo
    SubscribedSnssaiInfo:
      type: object
      properties:
        dnnInfos:
          type: array
          items:
            $ref: "#/components/schemas/Dnn"
    # SubscribedSnssaiInfos
    SubscribedSnssaiInfos:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/SubscribedSnssaiInfo"
    # SmfSelectionSubscriptionData
    SmfSelectionSubscriptionData:
      type: object
      properties:
        subscribedSnssaiInfos:
          $ref: "#/components/schemas/SubscribedSnssaiInfos"
    # AmPolicyData
    AmPolicyData:
      type: object
      properties:
        subscCats:
          type: array
          items:
            type: string
    # SmPolicyDnnData
    SmPolicyDnnData:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Dnn"
    # SmPolicySnssai
    SmPolicySnssai:
      type: object
      properties:
        snssai:
          $ref: "#/components/schemas/Nssai"
        smPolicyDnnData:
          $ref: "#/components/schemas/SmPolicyDnnData"
    # SmPolicySnssaiData
    SmPolicySnssaiData:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/SmPolicySnssai"
    # SmPolicyData
    SmPolicyData:
      type: object
      properties:
        smPolicySnssaiData:
          $ref: "#/components/schemas/SmPolicySnssaiData"
    # FlowRules
    FlowRules:
      type: object
      properties:
        filter:
          type: string
        precedence:
          type: integer
          format: int64
        snssai:
          type: string
        dnn:
          type: string
        qfi:
          type: integer
          format: int64
    QosFlows:
      type: object
      properties:
        snssai:
          type: string
        dnn:
          type: string
        qfi:
          type: integer
          format: int64
        5qi:
          type: integer
          format: int64
        mbrUL:
          type: string
        mbrDL:
          type: string
        gbrUL:
          type: string
        gbrDL:
          type: string
    # Subscription
    Subscription:
      type: object
      properties:
        userNumber:
          type: integer
          format: int64
        plmnID:
          type: string
        ueId:
          type: string
        AuthenticationSubscription:
          $ref: "#/components/schemas/AuthenticationSubscription"
        AccessAndMobilitySubscriptionData:
          $ref: "#/components/schemas/AccessAndMobilitySubscriptionData"
        SessionManagementSubscriptionData:
          type: array
          items:
            $ref: "#/components/schemas/SessionManagementSubscriptionData"
        SmfSelectionSubscriptionData:
          $ref: "#/components/schemas/SmfSelectionSubscriptionData"
        AmPolicyData:
          $ref: "#/components/schemas/AmPolicyData"
        SmPolicyData:
          $ref: "#/components/schemas/SmPolicyData"
        FlowRules:
          type: array
          items:
            $ref: "#/components/schemas/FlowRules"
        QosFlows:
          type: array
          items:
            $ref: "#/components/schemas/QosFlows"
